#!/bin/bash

print()
{
d=(null one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen)
	e=(null nullu twenty thirty fourty fifty sixty seventy eighty ninety)
		
	if [ $1 -eq 0 ]
	then
	x=0
	
	elif [ $1 -gt 9999999 ]
	then print $(($1/10000000))
	echo -n "crore "
	print $(($1%10000000))
	
	 
	elif [ $1 -gt 99999 ]
	then print $(($1/100000))
	echo -n "lakh "
	print $(($1%100000))
	 
	elif [ $1 -gt 999 ]
	then print $(($1/1000))
	echo -n "thousand "
	print $(($1%1000))
	
	
	elif [ $1 -gt 99 ]
	then print $(($1/100))
	echo -n "hundred "
	print $(( $1 % 100 ))
	
	elif [ $1 -gt 19 ]
	then x=${e[$(($1/10))]}
	echo -n "$x " 
	print $(( $1 % 10 ))
	else x=${d[$1]}
	echo -n "$x " 
	fi
	
}
read a
a=$(echo $a | sed 's/^0*//' )
b='^[0-9][0-9]*$'
if [[ $a =~ $b ]]
then
	
	if [ $a -eq 0 ]
	then echo zero
	else
	print $a
	fi

else 
echo invalid
exit -1
fi


